name: tmdb_movie_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^9.0.0
  go_router: ^13.2.0
  google_fonts: ^4.0.5
  oauth2: ^2.0.2
  shimmer: ^3.0.0
  skeletonizer: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Poppin
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
    - family: RRR
      fonts:
        - asset: assets/font/rrr.ttf
    - family: Roboto
      fonts:
        - asset: assets/font/roboto.ttf
